# frozen_string_literal: true

source 'https://rubygems.org'

gem 'omniauth-google-oauth2-apis', :git => 'https://github.com/timholbrook/omniauth-google-oauth2.git'
gem 'rubocop'
gem 'sinatra', '~> 1.4'
